### ISSUE TITLE
Shared element morphing

### ISSUE THREAD

**Issue by kkbhav** [fram-x/FluidTransitions#37]
Hi, would it be possible to morph images between a shared transition. I have a use case where images are different on 2 screens but the implementation requires shared transition between them. As of now, when transitioning from first screen to second, the image on second screen abruptly appears at the end of transition.

**Comment by chrfalch** [comment]
Hi @kkbhav! 

Since this is basically a shared element transition library, elements should be shared and not different from each other. On the other hand, this is a really cool feature to add, and I've been playing around with some constructs to add support for this. 

My first idea is to be able to provide an animatable property in the `Transition` class that will connect the navigation interpolation in a transition to the given property in the wrapped element. Example:

´´´jsx
<Transition shared="id" animatedProperty="time">
  <MyMorphableImage/>
</Transition>
´´´

When running the transition above the `MyMorphableImage` would be animated through its `time` property.

Would this be something of interest?

**Comment by Un3qual** [comment]
@chrfalch This sounds like a perfect solution, especially for things like lottie

**Comment by kkbhav** [comment]
@chrfalch Yes, this seems like a good approach to implement the functionality. The developer will be responsible for using this property, but as it will be add-on over the shared animation it will work great. 
Have you started working on this feature?

Also, I was going through the code and thought what if during the shared transition we animate both the react elements from start position to end position with opacity property so that if images are different it will give a look of shared animation. Is it do-able or will it cause too much performance issue during the transition?

**Comment by chrfalch** [comment]
Implemented in #47
