### ISSUE TITLE
Cant Use screen Interpolator

### ISSUE THREAD

**Issue by Kida007** [fram-x/FluidTransitions#67]
I dont want to use default transition b/w screens but something like this( default in React Navigation):

```
    transitionConfig: () => ({
      transitionSpec: {
        duration: 300,
        easing: Easing.out(Easing.poly(4)),
        timing: Animated.timing,
      },
      screenInterpolator: sceneProps => {
        const { layout, position, scene } = sceneProps;
        const { index } = scene;

        const height = layout.initHeight;
        const translateY = position.interpolate({
          inputRange: [index - 1, index, index + 1],
          outputRange: [height, 0, 0],
        });

        const opacity = position.interpolate({
          inputRange: [index - 1, index - 0.99, index],
          outputRange: [0, 1, 1],
        });

        return { opacity, transform: [{ translateY }] };
      },
    }),
```

But API didnt mention how we can use screenInterpolator.

**Comment by chrfalch** [comment]
Hi @Kida007, thanks for submitting an issue.

FluidNavigator does not support custom transitions like this - it will interpolate and transform individual elements on screen, not screens themselves. The default transition between two screens will be a fade. Will mark this as a feature request, but it will unfortunately not be prioritized by me - if you want to have a go, please feel free - I love PR's ;-)

**Comment by FlamingUber** [comment]
@chrfalch Quick question, every time I transition between screens it fades to white then to the next screen. Since my background is not white, this ruins the way the app looks (I want it to seem like the elements on the screen are moving while the background is static). Is this not possible? I am running the app on Android.

**Comment by chrfalch** [comment]
You should be able to style the background like this (from the ShoeShop-example):

```js
const Navigator = FluidNavigator({
  screen1: { screen: Screen1 },
  screen2: { screen: Screen2 },
}, {
  style: { backgroundColor: '#C14534' },
});
```

**Comment by FlamingUber** [comment]
This is helpful, but does this mean that if we have a gradient or image background we are out of luck?

**Comment by chrfalch** [comment]
It is difficult with the current implementation to remove the global opacity transition, but if you have two images or gradients of the same type on two screens they should blend just fine - we're doing that all the time ;-)

**Comment by Eddie-CooRo** [comment]
Hi, @chrfalch
any update on this???
actually, my company needs this feature and I it would be a pleasure if I can contribute something to this repository.
my problem is that our app has so many stack navigators which all of them are placed inside a single bottomBarNavigator, and transitionConfig is the same for all of them(translating from right)
but one of our screens requires a shared element transition and after examining the relative libraries, I've chosen this one because of its' awesome API & ease of use.

Let me explain the problem caused me stating this matter.
Consider the following structure:
```
FluidNavigator
├── AppSwitchNavigator
│   ├── AuthStackNavigator
│   │   ├──  ....
│   ├── BottomBarNavigator
│   │   ├── Homepage
│   │   ├── Profile
└── SharedElementScreen
```
Now when I navigate from Homepage to SharedElementScreen and vice-versa, everything is great,
But when I try to navigate to "Profile" from "SharedElementScreen", the shared image starts to move to its last location in Homepage Screen and then the "Profile" Screen becomes visible. but the desired behaviour is the default "translating from right" transition.
So I wonder whether we can turn shared element transition off for some navigations (Those don't have any shared element in destination or origin screen) and also develop a way to use custom screen interpolators when there are no needs for shared element transitions (I tried the SET with "translating from right" transition and everything was a mess 😂😂😂)
